blog/urls.py
from django.conf.urls import url, include
from .import views
from django.views.generic import ListView, DetailView
from .models import Post
from django.contrib.auth.decorators import login_required

app_name = 'blog' 
urlpatterns = [
	url(r'^add_post/$', views.add_post, name="add_post"),
	url(r'^$', login_required(views.postList.as_view(), login_url='personal:login'), name='postlist'),
	url(r'^detail/(?P<pk>[0-9]+)/$', views.blogDetail.as_view(), name='blogdetail'),
	url(r'^delete_post/(?P<post_id>[0-9]+)/$', views.delete_post, name='delete_post'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^', include('personal.urls')),
    url(r'^blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals

from django.db import models


class Post(models.Model):
	title = models.CharField(max_length = 140)
	body = models.TextField()
	date = models.DateTimeField()

	def __str__(self):
		return self.title

blog/forms.py
from django import forms
from .models import Post


class DateInput(forms.DateInput):
	input_type = 'date'


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'body', 'date']
		widgets = {
            'date': DateInput(attrs={'type': 'date'}),
        }
        

blog/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Post
from django.http import HttpResponse
from .forms import PostForm
from django.contrib.auth.decorators import login_required

def add_post(request):
	form = PostForm(request.POST or None)
	if form.is_valid():
		post = form.save(commit=False)
		post.save()
		return redirect('blog:postlist')
	context = {"form": form}
	return render(request, 'blog/add_post.html', context)


def delete_post(request, post_id):
	post = Post.objects.get(pk=post_id)
	post.delete()
	return redirect('blog:postlist')


class postList(generic.ListView):
	template_name = 'blog/blog.html'

	def login_required(self):
		return partial(login_required, login_url='personal:login')

	def get_queryset(self):
		return Post.objects.all().order_by("-date")[:25]


class blogDetail(generic.DetailView):
	model = Post
	template_name = 'blog/post.html'

blog/templates/blog/add_post.html
{% extends "personal/header.html" %}

{% block content %}
    <h3>Add a New Post</h3>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
    <form class="form-horizontal" role="form" action="{% url "blog:add_post" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
		    <div class="form-group">
		        <div class="col-sm-offset-2 col-sm-10">
		            <span class="text-danger small">{{ field.errors }}</span>
		        </div>
		        <label class="control-label col-sm-2" for="post_title">{{ field.label_tag }}</label>
		        <div class="col-sm-10">{{ field }}</div>
			 </div>
		{% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/blog.html
{% extends "personal/header.html" %}

{% block content %}
	<form action="{% url "blog:add_post" %}" >
		<button class="b">Add New Blog</button><br><br>
	</form>
	{% for post in object_list %}
		<h5>{{ post.date|date:"D, d-M-y" }}<a href="{% url 'blog:blogdetail' post.id %}">  {{ post.title }}</a></h5>
	{% endfor %}
{% endblock %}

blog/templates/blog/post.html
{% extends 'personal/header.html' %}

{% block content %}
<h3>{{ post.title }}</h3>
<h6>{{ post.date }}</h6>
{{ post.body|safe|linebreaks }}
<br><br>
<form action="{% url 'blog:delete_post' post.id %}" method="post">
	{% csrf_token %}
	<input type="hidden" name="post_id" value="{{ post.id }}" />
	<button class="b">Delete Post</button><br><br>
</form>
{% endblock %}