blog/urls.py
from django.conf.urls import url, include
from .import views
from django.views.generic import ListView, DetailView
from .models import Post
from django.contrib.auth.decorators import login_required

app_name = 'blog' 
urlpatterns = [
	url(r'^add_post/$', views.add_post, name="add_post"),
	url(r'^$', login_required(views.postList.as_view(), login_url='personal:login'), name='postlist'),
	url(r'^detail/(?P<pk>[0-9]+)/$', views.blogDetail.as_view(), name='blogdetail'),
	url(r'^delete_post/(?P<post_id>[0-9]+)/$', views.delete_post, name='delete_post'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^', include('personal.urls')),
    url(r'^blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/urls.py
from django.conf.urls import url
from .import views

app_name = 'personal'
urlpatterns = [
	url(r'^home/$', views.index, name='index'),
	url(r'^profile/$', views.profile, name='profile'),
	url(r'^$', views.login_user, name='login'),
	url(r'register/$', views.register, name='register'),
	url(r'logout/$', views.logout_user, name='logout'),
]

personal/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import date


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	BRANCH = (
		('CSE', 'CSE'),
		('MECH', 'MECH'),
		('ECE', 'ECE'),
		('EEE', 'EEE'),
		('CIVIL', 'CIVIL'),
		('META', 'META'),
		)
	SEX = (
		('M', 'Male'),
		('F', 'Female'),
		('N', 'Not Specific')
		)
	department = models.CharField(max_length=5, choices=BRANCH)
	picture = models.ImageField(upload_to='profile_pictures', default='default_pic.jpg')
	isAdmin = models.BooleanField(default=True)
	dob = models.DateField(default=date.today)
	gender = models.CharField(max_length=20, choices=SEX, default='N')

	def __str__(self):
		return self.user.username

personal/forms.py
from django import forms
from django.forms import ModelForm, widgets
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib import admin


class DateInput(forms.DateInput):
	input_type = 'date'

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	confirm_password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ['username', 'password', 'confirm_password']


class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ['dob',]
		widgets = {
            'dob': DateInput(attrs={'type': 'date'}),
        }


class UserForm2(ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name',]


class UserProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ['picture','department', 'gender',]

personal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserForm, UserProfileForm, UserProfileUpdateForm, UserForm2
from django.contrib.auth import authenticate,login,logout
from .models import UserProfile
from django.contrib.auth.decorators import login_required

IMAGE_FILE_TYPES = ['jpg', 'png', 'jpeg']


def index(request):
	if not request.user.is_authenticated():
		return redirect('personal:login')
	return render(request, 'personal/home.html')

@login_required(login_url='personal:login')
def profile(request):
	try:
		user_profile = UserProfile.objects.get(user=request.user)
	except UserProfile.DoesNotExist:
		return render(request, 'personal/profile.html', {'errors': 'User profile does not exist!'})

	update_user_form = UserForm2(data=request.POST, instance=request.user)
	update_profile_form = UserProfileUpdateForm(data=request.POST, instance=user_profile)
	if request.method == "POST":
		if update_user_form.is_valid() and update_profile_form.is_valid():
			user = update_user_form.save()
			profile = update_profile_form.save(commit=False)
			profile.user = user
			temp = profile.picture
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']
			file_type = profile.picture.url.split('.')[-1]
			file_type = file_type.lower()
			if file_type not in IMAGE_FILE_TYPES:
				profile.picture = temp
				context = {
				'update_user_form': update_user_form,
				'update_profile_form': update_photo_form,
				'errors': 'Image format not supported!',
				}
				return render(request, 'personal/profile.html', context)
			profile.save()
			return redirect('personal:index')
	context = {
		'update_user_form': update_user_form,
		'update_profile_form': update_profile_form,
	}
	return render(request, 'personal/profile.html', context)

def register(request):
	user_form = UserForm(request.POST or None)
	profile_form = UserProfileForm(request.POST or None)
	if user_form.is_valid() and profile_form.is_valid():
		user = user_form.save(commit=False)
		#print(user.username)
		username = user_form.cleaned_data['username']
		password = user_form.cleaned_data['password']
		confirm_password = user_form.cleaned_data['confirm_password']
		if password == confirm_password:
			user.set_password(password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			profile.save()
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('personal:index')
		else:
			context = {
				'user_form': user_form,
				'profile_form': profile_form,
				'error_message': 'Passwords do not match!',
			}
			return render(request, 'personal/register.html', context)
	context = {
		'user_form': user_form,
		'profile_form': profile_form,
	}
	return render(request, 'personal/register.html', context)


def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return render(request, 'personal/home.html')
		else:
			return render(request, 'personal/login.html', {'error_message': 'Invalid Credentials!'})
	return render(request, 'personal/login.html')


def logout_user(request):
	logout(request)
	form = UserForm(request.POST or None)
	context = {
		'form': form
	}
	return render(request, 'personal/login.html', context)

personal/templates/personal/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>My Site</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'personal/css/bootstrap.min.css' %}" type = "text/css"/>
	<script type="text/javascript" src="{% static 'personal/js/bootstrap.min.js' %}"></script>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	
	<style type="text/css" >
		html,
		body { 
		  	height:100%
		}
		.button {
    		background-color: white;
		    border: 3px solid #4CAF50;
		    color: black;
		    padding: 8px 15px;
		    text-align: center;
		    text-decoration: none;
		    display: inline-block;
		    font-size: 15px;
		    margin: 4px 2px;
		    -webkit-transition-duration: 0.4s; /* Safari */
    		transition-duration: 0.4s;
		    cursor: pointer;
		}
		.button:hover {
		    background-color: #4CAF50; /* Green */
		    color: white;
		}
	</style>
</head>
<body class="body" style="background-color: #f6f6f6">
	<div class="container-fluid" style="min-height:95%;">
		<div class="row">
			<div class='container-fluid' font-color='white'>
			<br><br>
			<font color="black">
			   {% block content %}
			   {% endblock %}
			   </font>
			</div>
		  </div>
		</div> 
	</div>
	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="#" target="blank">Contact</a> | <a href="#" target="blank">LinkedIn</a> | <a href="#" target="blank">Twitter</a> | <a href="#" target="blank">Google+</a></p>
		</div>
	</footer>	
	
</body>

</html>

personal/templates/personal/basic.html
{% extends "personal/header.html" %}

{% block content %}
	{% for d in content %}
		<p>{{ d }}</p>
	{% endfor %}

{% endblock %}

personal/templates/personal/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>My Site</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'personal/css/bootstrap.min.css' %}" type = "text/css"/>
	<script type="text/javascript" src="{% static 'personal/js/bootstrap.min.js' %}"></script>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	
	<style type="text/css" >
		html,
		body { 
		  	height:100%
		}
		.button {
    		background-color: white;
		    border: 3px solid #4CAF50;
		    color: black;
		    padding: 8px 15px;
		    text-align: center;
		    text-decoration: none;
		    display: inline-block;
		    font-size: 15px;
		    margin: 4px 2px;
		    -webkit-transition-duration: 0.4s; /* Safari */
    		transition-duration: 0.4s;
		    cursor: pointer;
		}
		.button:hover {
		    background-color: #4CAF50; /* Green */
		    color: white;
		}
	</style>
</head>

<body class="body" style="background-color: #f6f6f6" >
	<div class="container-fluid" style="min-height:95%; ">
		<div class="row">
			  <div class="col-sm-2">
				  <br>
				  <center>
					<img src="{{ request.user.userprofile.picture.url }}" class="responsive-img" style='max-height:100px;' alt="Profile Image">
				  </center>
			  </div>
			  <div class="col-sm-10">
				  <br>
				  <center>
				  <h3><font color="black">Programming, Learning, Building</font></h3>
				  </center>
			  </div>
		</div><hr>

		<div class="row">
		  <div class="col-sm-2">
		  <br>
		  <br>
			<!--<div class="well bs-sidebar affix" id="sidebar" style="background-color:#fff">-->
			<div class="well bs-sidebar" id="sidebar" style="background-color:#fff">
			  <ul class="nav nav-pills nav-stacked">
				<li><a href='/home/'>Home</a></li>
				<li><a href='/blog/'>Blog</a></li>
				<li><a href="/polls/">Polls</a></li>
				<li><a href='/profile/'>Profile</a></li>
				<li><a href='/logout/'>Logout</a></li>
			  </ul>
			</div> <!--well bs-sidebar affix-->
		  </div><hr> <!--col-sm-2-->
		  <div class="col-sm-10">
		  
			<div class='container-fluid' font-color='white'>
			<font color="black">
			   {% block content %}
			   {% endblock %}	
			   </font>
			</div>
		  </div>
		</div> 
	</div>
	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="#" target="blank">Contact</a> | <a href="#" target="blank">LinkedIn</a> | <a href="#" target="blank">Twitter</a> | <a href="#" target="blank">Google+</a></p>
		</div>
	</footer>	
	
</body>

</html>

personal/templates/personal/home.html
{% extends "personal/header.html" %}

{% block content %}
{% if request.user.first_name %}
	<p>Welcome {{ request.user.first_name }}</p>
{% else %}
	<p>Please complete your profile.</p>
{% endif %}
{% endblock %}

personal/templates/personal/login.html
{% extends 'personal/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'personal:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'personal:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

personal/templates/personal/profile.html
{% extends "personal/header.html" %}

{% block content %}
	{% if errors %}
		<p>{{ errors }}</p>
	{% endif %}
	<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ update_user_form.as_p }}
	{{ update_profile_form.as_p }}
	<div class="col-sm-offset-2 col-sm-10">
					    <button type="submit" class="btn btn-success">Submit</button>
					</div>
	
</form>
{% endblock %}

personal/templates/personal/register.html
{% extends 'personal/base.html' %}

{% block content %}

<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-md-6">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3>Register for an Account</h3>
						{% if error_message %}
						    <p><strong>{{ error_message }}</strong></p>
						{% endif %}
						{% for field in user_form %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<span class="text-danger small">{{field.errors}}</span>
							</div>
							<label class="control=label col-sm-2">{{ field.label_tag }}</label>
							<div class="col-sm-10">{{ field }}</div>
						</div>
						{% endfor %}
						{% for field in profile_form %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<span class="text-danger small">{{field.errors}}</span>
							</div>
							<label class="control=label col-sm-2">{{ field.label_tag }}</label>
							<div class="col-sm-10">{{ field }}</div>
						</div>
						{% endfor %}
						<div class="col-sm-offset-2 col-sm-10">
					        <button type="submit" class="btn btn-success">Submit</button>
					    </div>
					</div>
				    <div class="panel-footer">
				        Already have an account? <a href="{% url 'personal:login' %}">Click here</a> to log in.
				    </div>
				</div>
			</div>
		</div>
	</div>
</form>

{% endblock %}